sadcd-bootstrap starts chunk server daemon
CS297P-SAD/sadfs pull request #19
Opened 2020-10-28 22:11 UTC by abmono93

closes #7

2020-10-28 23:16 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +		memcpy(port_str, &(config["port"].as<std::uint16_t>()), 2);
This doesn't do what we want it to do. `memcpy` copies the `std::uint16_t` byte-wise into a `char` array. What we want is a string representation of the port number, like `"6666"`, perhaps created using https://en.cppreference.com/w/cpp/string/basic_string/to_string.

2020-10-28 23:19 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	char *const chunk_argv[] = {port_str, NULL};
When `sadcd` starts running, its `argv` should look something like this:  
`{ "sadcd", "--port", "6666", nullptr }`

2020-10-28 23:23 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	char port_str[2];
Let's use `auto` instead of explicitly mentioning types wherever possible, and use `std::array` instead of naked, C-style arrays. Something like `auto chunk_argv = std::array<char const*, argc+1>`.

2020-10-28 23:27 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	char *const chunk_argv[] = {port_str, NULL};
As per convention, the first (0th) element in `argv` should be the name of the program.

2020-10-28 23:31 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	errno = 0;
The OS and the C standard library set `errno` when something goes wrong. So, we must use it as a read-only variable unless we write a C function that needs to indicate an error condition.

2020-10-28 23:34 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	}else{
This is really me nit-picking, but it'll probably be cleaner to check for a missing port number, and show an error if it *is* missing. We can do it with a single `if` block instead of `if` and `else`.

2020-10-28 23:36 UTC, damanmkumar commented on src/sadcd/sadcd.cpp
> +#include <iostream>
Let's add a comment at the top of the file to indicate what the code in this file does.

2020-10-28 23:37 UTC, damanmkumar requested changes
Caught a couple of errors, and some general comments.

2020-10-28 23:45 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +		memcpy(port_str, &(config["port"].as<std::uint16_t>()), 2);
Yes I see what you're saying but to_string will create an std::string, which I don't think execve will accept. But yes I need to figure out a way to get a C string representation of the port

2020-10-28 23:52 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	}else{
Yes I agree that is a better way to do it

2020-10-29 00:10 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +		memcpy(port_str, &(config["port"].as<std::uint16_t>()), 2);
https://en.cppreference.com/w/cpp/string/basic_string/c_str is your friend :)

2020-10-29 00:41 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	char *const chunk_argv[] = {port_str, NULL};
Thanks, I just rewrote this whole section in a way that hopefully address this and your other comments. Lemme know what you think

2020-10-29 00:45 UTC, abmono93 commented on src/sadcd/sadcd.cpp
> +#include <iostream>
At the moment this file only needs to be here to verify if a sadcd-bootstrap call to execve() works. I will add some behavior to it for my next pull request and include a description

2020-10-29 01:41 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	char sadcd_str[] = "sadcd";
We don't need temporary variables to store a pointer to these string literals. They can be declared while initializing the `argv` array.

2020-10-29 01:41 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	char port_arg_str[] = "port";
Should be `--port`

2020-10-29 01:44 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	strncpy(port_str, port.c_str(), sizeof(char) * port.size());
- We don't need to copy the contents of the `port` into another buffer. All we need is a pointer to the buffer that `std::string` internally maintains, which is what `std::string::c_str()` gives us.

2020-10-29 01:48 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	char sadcd_str[] = "sadcd";
You're right it's not necessary but I changed it to be this way because declaring them in the array initializer causes a compilation warning

2020-10-29 01:51 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	strncpy(port_str, port.c_str(), sizeof(char) * port.size());
I originally just had 'std::array<char *, 4> chunk_argv = {sadcd_str, port_arg_str, port.c_str() , NULL};' but it doesn't allow me to compile it this way

2020-10-29 01:52 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	strncpy(port_str, port.c_str(), sizeof(char) * port.size());
src/sadcd/sadcd-bootstrap.cpp:120:63: error: cannot initialize an array element of type 'char *'
      with an rvalue of type 'const std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >::value_type *' (aka 'const char *')
        std::array<char *, 4> chunk_argv = {sadcd_str, port_arg_str, port.c_str() , NULL};

2020-10-29 01:53 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	char port_arg_str[] = "port";
Thanks I'll change this

2020-10-29 02:01 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	std::array<char *, 4> chunk_argv = {sadcd_str, port_arg_str, port_str, NULL};
String literals like `"sadcd"` and `"--port"` can be declared here as:
`auto chunk_argv = std::array<char const*, 4>{ "sadcd", "--port", port.c_str(), nullptr };`

Also `nullptr` is C++ equivalent to C's `NULL`.

2020-10-29 02:02 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	std::cerr << "Error: could not start chunk server: " <<
Wait, since `main` shows an error message if `start_server` returns, we don't need the error handling here. Or in `main`. Your call!

2020-10-29 02:02 UTC, damanmkumar requested changes
A few more comments

2020-10-29 02:07 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	strncpy(port_str, port.c_str(), sizeof(char) * port.size());
Yup, that's because `port.c_str()` returns a `char const*` since it doesn't expect us to overwrite the string it contains/owns (when we use `c_str()`). And if you think about it, `execve` doesn't ask for a mutable `char*` since it only reads the strings, and doesn't overwrite them. So, `chunk_argv` should be an array of pointers to immutable `char`s, aka `char const*`.

2020-10-29 02:13 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	std::array<char *, 4> chunk_argv = {sadcd_str, port_arg_str, port_str, NULL};
We could do it this way but we'd get a bunch of warnings every time we run make:

Adams-MBP-3:sadfs adammonahan$ make chunk
g++ -c -std=c++17 -ggdb -O -Iinclude        src/sadcd/sadcd-bootstrap.cpp -o build/sadcd/sadcd-bootstrap.o
src/sadcd/sadcd-bootstrap.cpp:120:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        std::array<char *, 4> chunk_argv = {"sadcd", "--port", port_str , NULL};
                                                                     ^
src/sadcd/sadcd-bootstrap.cpp:120:47: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
        std::array<char *, 4> chunk_argv = {"sadcd", "--port", port_str , NULL};
                                                                                    ^
2 warnings generated.

2020-10-29 02:16 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	strncpy(port_str, port.c_str(), sizeof(char) * port.size());
Why would `strncpy`cause the program crash?

2020-10-29 02:17 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	std::array<char *, 4> chunk_argv = {sadcd_str, port_arg_str, port_str, NULL};
See https://github.com/CS297P-SAD/sadfs/pull/19#discussion_r513878175

2020-10-29 02:18 UTC, abmono93 commented on src/sadcd/sadcd-bootstrap.cpp
> +	std::cerr << "Error: could not start chunk server: " <<
Yes that's true. I found having the message here helpful while debugging because execve gave me hints as to what I did wrong with errno. Although I suppose it would still be available after it returns to main

2020-10-29 02:25 UTC, damanmkumar commented on src/sadcd/sadcd-bootstrap.cpp
> +	strncpy(port_str, port.c_str(), sizeof(char) * port.size());
When we declare `port_str` as a `char*`, it is not initialized, and will contain some garbage data (say `0x326b123e`). Then, `strncpy` will go and write the data contained in the string `port` at the memory location pointed to by `port_str`. If the program doesn't have access to `0x326b123e`, it will crash. If it does have write access to that memory location, however, it will silently overwrite some data elsewhere in the program.  

`strncpy` expects the address of a buffer. `port_str` should really be a `char` array if we were to use this.

2020-10-29 03:36 UTC, damanmkumar approved these changes
Let's get this moving, haha

2020-10-29 03:38 UTC, merged