Create sadmd data structures, database and load database contents
CS297P-SAD/sadfs pull request #29
Opened 2020-11-13 01:02 UTC by abmono93

The exact info sadmd keeps about files and chunk servers is based on what is currently in ideas.md but will likely change and it should be straigtforward to do so.

If you manuallly add some rows to the database this will print the filenames and chunkid lists as there is no other way to verify that this works but these print statements should be removed once there is some more functionality associated with the files_ object

Closes #28

2020-11-13 03:51 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +#include <ctime>
Let's use the more modern `std::chrono` here?

2020-11-13 03:53 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	inet::ip_addr ip;
`inet::service` is a better fit here since the chunk server really provides a service, and it is intended to abstract IP + port number into a logical entity.

2020-11-13 03:59 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	int total_space;
`int` is small and signed. It might make sense to use a 4-byte integer to save memory, while counting number of chunks currently stored, and max number of chunks that the server can accommodate. `unsigned` or `std::size_t` will be better.

2020-11-13 05:10 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +#include <ctime>
Yea good idea

2020-11-13 05:12 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	inet::ip_addr ip;
Well yes but the main use of this will be to send this info to a client so they know where to read or write from. Would it make sense to send an `inet::service` object over the network?

2020-11-13 05:18 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	time_t ttl;
Since we'll be using the `std::chrono` library, we can use a regular integer to store the TTL.
There are ways to encode the current time into a regular integer type. While setting the TTL,
we can store the time, say ten minutes from now, into such an integer. That way, we can determine when the `{chunk_server|file}_info` has expired.
[`std::chrono::steady_clock`](https://en.cppreference.com/w/cpp/chrono/steady_clock) is recommended when dealing with the time duration between events.

Here's something I quickly put together. We will probably need better names.

2020-11-13 05:21 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	int total_space;
I wasn't sure about this since I didn't know if this should mean number of bytes, kb or what so I went with the most straigtforward thing. But now that you say it number of chunks is a nice suggestion. And also yes it can be unsigned but not sure we would save much space using `std::size_t` as this will be one per chunk server

2020-11-13 05:24 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	inet::ip_addr ip;
We will be sending the IP and port number in a control message. We can use `ip()` and `port()` to retrieve them anyway. Also, using `inet::service` has the added advantage of making sure there is no possibility of IPs and port numbers getting mixed up between different objects.

2020-11-13 05:32 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	inet::ip_addr ip;
Also, we should be sending the ip as a string, and the port number as a regular 16-bit number over the network. So, `ip_addr` should either store the string passed to it, or convert the network byte representation into a `std::string` on demand. Same with the port number.

2020-11-13 06:23 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	int total_space;
We will save space if we use `unsigned` since it is 4 bytes on most platforms. `std::size_t` is 8 bytes on 64-bit platforms, which are the most common.

2020-11-13 06:25 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	time_t ttl;
Is the TTL here for the lock held by a client? If so, we can get rid of the `bool`. If the TTL is "valid," the lock is held. Otherwise, it is free. What do you think?

2020-11-13 06:27 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	std::vector<int> chunkids;
Chunk IDs should be globally unique numbers. They should definitely be unsigned integers.

2020-11-13 06:42 UTC, damanmkumar commented on src/CMakeLists.txt
> +target_link_libraries(sadmd
Let's move this further down the file so that things are organized

2020-11-13 06:54 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +db_command(std::string stmt)
Since we're not modifying the string, and since we may call this function by passing a string constructed at runtime, let's pass the parameter `stmt` by `const&` to avoid making a copy. The `const` will help the compiler perform any possible optimizations.

2020-11-13 07:00 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	auto chk = sqlite3_exec(files_db_, stmt.c_str(), NULL, NULL, NULL);
Can we do away with `chk` here? How about something like `if (sqlite_exec(...) != 0)` ?

2020-11-13 07:20 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	sqlite3* db;
Is this temporary variable necessary?

2020-11-13 07:30 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +		std::cerr << "Error: Couldn't open database: ";
This error condition needs to be handled. Now, the program will continue to execute and run `db_command` even when `sqlite3_open` fails.

2020-11-13 08:32 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +create_file(std::string filename)
passing the filename parameter by value unnecessarily makes a copy of the `std::string` here. `std::string const&` will avoid that

2020-11-13 08:33 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	if (!files_.count(filename))
Should this method handle the edge case where it is invoked with a file that already exists? Is it an error when such a thing happens?

2020-11-13 08:41 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	sqlite3* files_db_;
If we never reassign `files_db_` to another database throughout the lifetime of `sadmd`, `files_db_` should be `const`. Introducing a method that performs the necessary setup and error handling like the `parse_*` methods in inet.cpp will help us initialize this member variable.

2020-11-13 08:48 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	void db_command(std::string);
Since `db_command` does not modify any of the member variables in this class, it should be marked `const`. And all functions that do not throw exceptions should be marked `noexcept`.

2020-11-13 08:54 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	std::vector<chunk_server_info> active_chunk_servers_;
When we receive updates/heartbeats from chunk servers, we will need to update the TTL in these info objects. If we use a `std::vector`, we'll need to linearly scan it to find the info object, which is an `O(n)` operation. Since this will happen continuously, it will not scale. We'll be better off using a faster data structure.

2020-11-13 08:56 UTC, damanmkumar requested changes
I left a bunch of comments, most of which are minor

2020-11-13 18:43 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	time_t ttl;
At one point I had this as a function `bool locked()` which would decide based on ttl. But then when thinking about how create_file() would work I realized files should be unlocked by default. So in order for that to work we'd need to decide on some convention for what the appropriate ttl is for a file that has never been locked. A straightforward way to do it which I only now thought of would be to set the ttl to one second  in the past, then locked() will return false iff ttl is before the current time. How's that sound?

2020-11-13 18:46 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +db_command(std::string stmt)
`std::string const&` or `const std::string&` ?

2020-11-13 18:49 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +		std::cerr << "Error: Couldn't open database: ";
Right. Do you think just exiting the program works?

2020-11-13 18:53 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	if (!files_.count(filename))
I was thinking this should just behave the way it does on a terminal. e.g. if I run  `touch tmp` twice the second time has no effect. And if I run `'touch existingfile` the contents of existingfile remain unchanged. So I would argue it should not be not an error

2020-11-13 18:58 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	sqlite3* files_db_;
We need a variable of type `sqlite3*` to pass to functions like `sqlite3_open()` and `sqlite3_exec`

2020-11-13 19:00 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	time_t ttl;
A function is an awesome idea. The specification for `std::chrono::steady_clock` says that it always monotonically increases. A TTL of `0` would implicitly mean that the file has been free since the beginning of time.

2020-11-13 19:01 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +db_command(std::string stmt)
I've used the first convention throughout the code base so far. So, let's go with that!

2020-11-13 19:03 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +		std::cerr << "Error: Couldn't open database: ";
It is a fatal error if the server cannot read the database. So, exiting sounds like the right approach.

2020-11-13 19:13 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	std::vector<chunk_server_info> active_chunk_servers_;
I think that depends on what these heartbeat messages will have in them. Would we just hash the ip? Or maybe there is a better way to do that, e.g. if retrieving the ip address of the incoming chunk server every time would be tedious, we can have the chunk server be aware of its assigned id number and provide that in the message. Then just use that id number as the index in this vector.

If we can't answer that now I'd suggest we leave this as it is until we can. Looping through a vector will not slow our tests down during development anyway since we'll have at most 2 or 3 chunk servers

2020-11-13 19:17 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	if (!files_.count(filename))
`touch` actually updates the last accessed time of a file. You can see it with `$ ls -l file`. So, the second `touch` technically does modify the file. What happens when a client requests a create operation on a file that already exists should ideally be a higher level decision. By having `create_file` take the decision to silently let this happen, we're giving it more responsibility than it should have.

`create_file` now has two responsibilities. Creating a file, and deciding what happens when a file exists already.

2020-11-13 19:19 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	sqlite3* files_db_;
Yes! I'm talking about `sqlite3* const files_db_` and not `sqlite3 const* files_db_`

2020-11-13 20:11 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	std::vector<chunk_server_info> active_chunk_servers_;
Yeah, the chunk server will need to identify itself when it sends a heartbeat message. I can think of two ways we can implement this.

The simplest approach is to have the chunk server send its ID, which we can use as a key. Using its IP address to identify it will not be a good idea from a correctness perspective. A crashed chunk server might get a new IP address on recovery. Hashing a `std::string` will introduce unnecessary overhead at runtime. So, a unique ID is the better approach here.

Another way we could do it is assign IDs to chunk servers starting from 0, in the order they contact the master server. This will let us use the ID as an index, but it is extra work that the master server has to do.

I suggest we design these things keeping our use cases in mind. At least as much as possible. Otherwise, we'll end up refactoring a lot of things once we start implementing higher level functionality.

2020-11-13 21:31 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	std::vector<chunk_server_info> active_chunk_servers_;
> it is extra work that the master server has to do
It doesn't seem like a lot of extra work to do something like
`id=active_chunk_servers.size()' and then `active_chunk_servers.emplace_back()`
in terms of actual computation I would guess it is less than the extra overhead of a hash lookup for each heartbeat

The only alternative I see is `std::unorderd_map<unsigned_int, chunk_server_info>'  . Do you think that'd be better? Or do you have something else in mind?

2020-11-13 23:20 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +using chunkid = uint64_t;
Let's call this uuid, since we'll need to use it for identifying chunks, chunk servers, and any other things we might need to uniquely identify.

2020-11-13 23:21 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	uint64_t total_space;
`{total|used}_space` will need to be renamed since we're encoding the number of chunks stored. Maybe `max_chunks` and `stored_chunks` or anything else you might deem fit.

2020-11-13 23:22 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	int ttl;
`ttl` should not be a signed integer, right?

2020-11-13 23:33 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	bool locked();
Since we aren't implementing `locked()` yet, let's remove it now and introduce it when we implement it.

2020-11-13 23:35 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +using chunkid = uint64_t;
Actually, I'm not opposed to `chunkid` since it is more readable.

2020-11-13 23:37 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +using chunkid = uint64_t;
The motive behind this was to differentiate when I'm talking about chunkids vs. some other unsigned integer. I just feel like chunkids show up all over the place  - they're used in file_info, as keys in the chunkids_ map, stored in the database, and will be passed around in almost every read/write control message - so it makes sense to give them an easily identifiable name. Chunk server ids are used in a more specific context (they are basically there for the master to keep track of them in the context of a single data structure) so I didn't think the same thing applied

2020-11-13 23:37 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	const inet::service service_;
Let's stick to the "east const" notation, which will make this `inet::service const service_;` to be consistent across our code base.

2020-11-13 23:39 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	uint64_t total_space;
Yes `*_chunks` is much clearer

2020-11-13 23:40 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	std::unordered_map<chunkid, std::vector<chunk_server_info*> > chunkids_;
`chunkids_` sounds like a collection of `chunkid`s, right? And this is more of a collection of chunk servers.

2020-11-13 23:43 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	int ttl;
I switched from `time_t` to  `int` because you said above it can be represented in a regular integer. I've never used chrono so I was just taking your word for it haha. 

You think it should be `unsigned int`?

2020-11-13 23:47 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	std::unordered_map<chunkid, std::vector<chunk_server_info*> > chunkids_;
Maybe we can rename the current `chunk_servers_` data structure to `chunk_server_metadata`, and `chunkids_` to `chunk_servers`. That way, this is what our code will look like:
```
chunk_server_metadata[server_id] // refers to metadata belonging to chunk server specified by id
chunk_servers[chunk_id]          // refers to a list of servers that host chunk_id
```

2020-11-13 23:49 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +	std::unordered_map<chunkid, std::vector<chunk_server_info*> > chunkids_;
I guess it is kind of like a dictionary with one entry for each `chunkid` that tells you where you can find that chunk. And the most straightforward way to get a list of all chunks in the system would be to iterate through this map. Whereas `chunk_servers_` is the authoritative list of chunk servers. But if there is a more obvious naming convention I am open to it. maybe `chunk_locations_` ?

2020-11-13 23:52 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	int ttl;
Ah, sorry! It should definitely be `std::chrono::steady_clock::duration::rep` but aliased as something more readable. Let's leave it as an `int` for now. We can use a more suitable type once we implement TTL. I'll try to quickly put something together tonight.

2020-11-14 00:08 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +			std::cerr << sqlite3_errmsg(files_db_) << '\n';
This needs to be formatted. Looks like there's an extra tab.

2020-11-14 00:09 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +		auto filename = std::string{reinterpret_cast<const char*>(sqlite3_column_text(stmt, 0))};
Is this line longer than 79 characters? Lets stick to that limit. It's a standard of sorts. Super long lines get wrapped to another line in my editor.

2020-11-14 00:11 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +open_db()
Lets also move all functions that need not be exposed to code in other `.cpp` files into `unnamed namespace`s. The compiler can perform some really cool optimizations that way.

2020-11-14 00:18 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +open_db()
That would apply to most of the functions in this file, right? Should I just wrap the whole class in an unnamed namespace?

2020-11-14 00:28 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +open_db()
If you don't see the need in a function being linked to from another `.cpp` file, throw it into an unnamed namespace. In fact, `open_db` is a utility function, right? There's no reason it should be a member function of `sadmd`. So, you can remove it from the private section of the class in `sadmd.hpp` as well. If a function isn't using a class's member variables/functions, let's just make it a utility function and keep the interface clean.

2020-11-14 00:28 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +open_db()
Wait sorry.. that would apply to all private functions though right? i.e. `process_message`

2020-11-14 05:04 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +		std::cerr << "Error running {" << stmt << "}: ";
We'll need to handle this error as well.

2020-11-18 07:27 UTC, damanmkumar approved these changes

2020-11-18 07:27 UTC, merged