Created sadfuse class and sadfsd-bootstrap
CS297P-SAD/sadfs pull request #30
Opened 2020-11-13 21:39 UTC by shu-g

* Implemented a bare bones fuse wrapper
* Modified CMakeFile to support libfuse
* Added sadfsd-bootstrap file

2020-11-18 23:41 UTC, abmono93 approved these changes

2020-11-18 23:41 UTC, abmono93 commented on doc/ideas.md
> +	Metadata Content Table
Are you thinking we will have a table like this in addition to the ones described below?

2020-11-19 03:52 UTC, shu-g commented on doc/ideas.md
> +	Metadata Content Table
Yeah, I think we can have Directory Content Table, Metadata Content Table, Chunks Table and Chunk Servers Table.
From an inode number in query, we can lookup files in that directory in the DC table.
For more info about file, we can lookup inode in MC table.
If we get read request, from the MC table, we'll get mapping to chunks in the C table and CS table.

2020-11-20 02:10 UTC, damanmkumar commented on src/CMakeLists.txt
> +add_executable (sadfsd-bootstrap
Adding the executable and letting CMake know that Boost's program_options should be linked should be done in the foreach loop like  we do for `sadmd` and `sadcd`. Any sadfsd-specific configuration can be done separately.

2020-11-20 02:10 UTC, damanmkumar commented on src/CMakeLists.txt
> +    PRIVATE ${FUSE_CFLAGS})
Not a review comment. What is the significance of `FUSE_CFLAGS` here?

2020-11-20 02:12 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +    static sadfuse& instance();
Why does `sadfuse` need to be a singleton class? It's purpose is to "set up" fuse, right?

2020-11-20 02:16 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +    fuse_operations& operations();
If `load_operations()` sets up `operations_`, why does `sadfuse` need to publicly expose it?

2020-11-20 02:40 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +    std::shared_ptr<sadfs::socket> master_socket_;
Our master server isn't designed to handle long standing connections with clients. Every request must be a separate connection.

2020-11-20 02:46 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +    sadfs::sadfuse& sadfuse = sadfs::sadfuse::instance();
The file needs to be formatted correctly.

2020-11-20 02:47 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +    std::array<std::string, 2> fuse_args = std::array
We're using the `auto <name> = <type>{...};` syntax throughout the code base.

2020-11-20 02:48 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +    int status = sadfuse.run(fuse_args.size(), fuse_argv.data());
This should be `auto status...` as well

2020-11-20 02:50 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +    static int getattr(const char* path, struct stat* stbuf);
We're using the "east const" notation in our code base. So, this would be `char const*`.

2020-11-20 02:53 UTC, damanmkumar commented on src/sadfsd/sadfuse.cpp
> +    operations_.getattr = &getattr;
This is more of a nit. Formatting this like
```
    operations_.getattr  = &getattr;
    operations_.readlink = nullptr;
    operations_.mknod    = nullptr;
    operations_.mkdir    = nullptr;
```
will be easier to read and parse.

2020-11-20 03:07 UTC, damanmkumar commented on src/sadfsd/sadfuse.cpp
> +    memset(&operations_, 0, sizeof operations_);
There's no reason to call `memset` here. The struct is zero-initialized if `sadfuse`'s constructor is called.

2020-11-20 03:10 UTC, damanmkumar commented on src/sadfsd/sadfuse.cpp
> +    static sadfuse instance;
This syntax will not initialize the `operations_` member variable of `sadfuse`. Use `auto instance = <type>{};` to avoid calling `memset`.

2020-11-20 03:12 UTC, damanmkumar commented on src/sadfsd/sadfuse.cpp
> +    return fuse_main(argc, argv, &operations(), this);
Why not `&operations_`? That is what the compiler will do anyway.

2020-11-20 03:18 UTC, damanmkumar requested changes
made a few comments

2020-11-21 00:38 UTC, shu-g commented on src/CMakeLists.txt
> +    PRIVATE ${FUSE_CFLAGS})
The compile flags for fuse contain path to include directories.

2020-11-21 00:39 UTC, shu-g commented on include/sadfs/sadfsd/sadfuse.hpp
> +    static sadfuse& instance();
Initial thought was that I should use global functions for the set up or create class with single instance. But now, I've modified the program so that this is normal class and made operations_ a static member.

2020-11-21 00:39 UTC, shu-g commented on include/sadfs/sadfsd/sadfuse.hpp
> +    fuse_operations& operations();
You're right, changed it.

2020-11-21 00:41 UTC, shu-g commented on include/sadfs/sadfsd/sadfuse.hpp
> +    std::shared_ptr<sadfs::socket> master_socket_;
Since there is no empty constructor for socket and wasn't initializing in sadfuse constructor, had to use shared_pointer.
Modified it to be an object of inet::service.

2020-11-21 00:41 UTC, shu-g commented on src/sadfsd/sadfuse.cpp
> +    operations_.getattr = &getattr;
You're right.

2020-11-21 01:17 UTC, shu-g commented on src/CMakeLists.txt
> +add_executable (sadfsd-bootstrap
Had to move add_dependency out of the loop, let me know if more changes are required.

2020-11-21 06:31 UTC, damanmkumar commented on src/CMakeLists.txt
> +    PRIVATE ${FUSE_CFLAGS})
Isn't that handled by `FUSE_INCLUDE_DIRS`?

2020-11-21 06:41 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +    inet::service master_service_;
If our `read`, `open`, and other `static` functions need to access `master_service_`, it needs to be `static` as well.

2020-11-24 20:33 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +#include <memory> // std::shared_ptr
This include will no longer be required since we do not need a `std::shared_ptr`

2020-11-24 20:36 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +class sadfuse
The purpose of this class is to set up FUSE, but what it really is doing is setting up the file system on the client machine, right? The name `sadfuse` is kinda exposing an implementation detail (that we're using FUSE). I feel `sadfs-bootstrap` is a better-suited name. Thoughts? @abmono93 , what do you think?

2020-11-24 20:43 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +            variables["ipaddress"].as<std::string>().data(),
`variables["ipaddress"].as<std::string>().c_str()` might express the intention better.

2020-11-24 20:45 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +	auto get_ptr = [](auto& str) { return str.data(); };
`str.c_str()` expresses the idea better. We should correct this in `sadmd` and `sadcd` as well.

2020-11-24 22:45 UTC, abmono93 commented on include/sadfs/sadfsd/sadfuse.hpp
> +class sadfuse
This is basically the client process's analogue of of `sadmd` and `sadcd` right? So how about `sadfsd`?

2020-11-24 22:48 UTC, abmono93 commented on src/sadfsd/sadfsd-bootstrap.cpp
> +    auto status = sadfuse.run(fuse_args.size(), fuse_argv.data());
Shouldn't run() be called from a process that is spawned by the bootstrap process? The way this is setup there will be an executable called sadfsd-bootstrap running as long as the user is running our filesystem, right?

2020-11-24 22:54 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +class sadfuse
The problem here is that the `d` stands for daemon, and this class isn't a daemon.

2020-11-24 23:00 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +    auto status = sadfuse.run(fuse_args.size(), fuse_argv.data());
No, fuse runs a different way. The `run()` function will basically tell the kernel/fuse which functions it/they should call for each operation (read, write, ...) and return immediately. At this point the remote file system is "mounted."

Any subsequent calls to these operations within that mounted file system will be redirected to our functions, which are the static functions in this class.

2020-11-24 23:01 UTC, abmono93 commented on src/sadfsd/sadfuse.cpp
> +    return fuse_main(argc, argv, &operations_, this);
Where is fuse_main defined?

2020-11-24 23:16 UTC, abmono93 commented on include/sadfs/sadfsd/sadfuse.hpp
> +class sadfuse
Right. How about something like `filesys` or `sadfilesys` ?

2020-11-24 23:18 UTC, damanmkumar commented on src/sadfsd/sadfuse.cpp
> +    return fuse_main(argc, argv, &operations_, this);
It's defined in `fuse.h`. This brings up a good thing. We should definitely be calling this function (and all functions we haven't written) as `::fuse_main(...)`

2020-11-24 23:19 UTC, damanmkumar commented on src/sadfsd/sadfuse.cpp
> +    return fuse_main(argc, argv, &operations_, this);
Question for @shu-g : Why are we passing in the `this` pointer here?

2020-11-24 23:40 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +class sadfuse
Either of those should work for now. Also, I just realised a problem here, and raised issue #42

2020-11-27 16:06 UTC, shu-g commented on src/CMakeLists.txt
> +    PRIVATE ${FUSE_CFLAGS})
I thought so too, but was getting linking errors on macOS without them.

2020-11-27 17:48 UTC, shu-g commented on include/sadfs/sadfsd/sadfuse.hpp
> +#include <memory> // std::shared_ptr
Using static shared pointer to master service. Assignment of inet::service was failing because the member ip_ and port_ are declared const.

2020-11-27 17:49 UTC, shu-g commented on src/sadfsd/sadfsd-bootstrap.cpp
> +            variables["ipaddress"].as<std::string>().data(),
Done

2020-11-27 17:49 UTC, shu-g commented on src/sadfsd/sadfsd-bootstrap.cpp
> +	auto get_ptr = [](auto& str) { return str.data(); };
Done

2020-11-27 18:13 UTC, shu-g commented on src/sadfsd/sadfuse.cpp
> +    return fuse_main(argc, argv, &operations_, this);
4th parameter is used to pass private data that gets stored in fuse context, in our case this is used to pass master_service_ and operations_

2020-11-27 18:14 UTC, shu-g commented on include/sadfs/sadfsd/sadfuse.hpp
> +class sadfuse
Lets do sadfilesys then

2020-11-27 18:44 UTC, shu-g commented on src/sadfsd/sadfsd-bootstrap.cpp
> +	auto get_ptr = [](auto& str) { return str.data(); };
C++17 onwards data() returns char*, c_str() returns char const*.
Since fuse_main expects char*, we need to use data()

2020-11-28 23:35 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfilesys.hpp
> +    int run(int argc, char** argv);
`run` isn't an appropriate name in this context. `fs.run()` does not read right. How about `bootstrap`?

2020-11-28 23:36 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfilesys.hpp
> +    // returns static pointer to object of this class
This comment doesn't explain what this method really does. We should mention that it gets the pointer from `fuse_context()`

2020-11-28 23:38 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfilesys.hpp
> +    static fuse_operations operations_;
This no longer needs to be `static` right?

2020-11-28 23:40 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfilesys.hpp
> +#include <memory> // std::shared_ptr
This header is not required anymore

2020-11-28 23:43 UTC, damanmkumar commented on include/sadfs/sadfsd/sadfuse.hpp
> +#endif // SADFS_SADFSD_SADFUSE_HPP
This file should be deleted

2020-11-28 23:57 UTC, damanmkumar commented on src/sadfsd/sadfilesys.cpp
> +#include <cstring> // memset()
No longer required, correct?

2020-11-28 23:58 UTC, damanmkumar commented on src/sadfsd/sadfilesys.cpp
> +    master_service_.connect();
If this statement is here for testing, we can add this line while testing on dev machines. Let's not push it to github.

2020-11-29 00:00 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +	auto get_ptr = [](auto& str) { return str.data(); };
I wonder why a lot of these interfaces expect non-const pointers when they only read from them

2020-11-29 00:01 UTC, damanmkumar commented on src/sadfsd/sadfsd-bootstrap.cpp
> +	};
The formatting is off, here

2020-11-29 00:02 UTC, damanmkumar commented on src/sadfsd/sadfuse.cpp
> +/* Definitions for the sadfuse class */
This file needs to go as well!

2020-11-29 00:03 UTC, damanmkumar requested changes
A few minor comments

2020-11-29 03:52 UTC, shu-g commented on src/sadfsd/sadfuse.cpp
> +/* Definitions for the sadfuse class */
Yup

2020-11-29 03:57 UTC, shu-g commented on src/sadfsd/sadfsd-bootstrap.cpp
> +	};
Oh, looks fine on my editor.

2020-11-29 03:58 UTC, shu-g commented on src/sadfsd/sadfilesys.cpp
> +    master_service_.connect();
Ok.

2020-11-29 04:01 UTC, shu-g commented on src/sadfsd/sadfilesys.cpp
> +#include <cstring> // memset()
Oh right.

2020-11-29 04:01 UTC, shu-g commented on include/sadfs/sadfsd/sadfilesys.hpp
> +    static fuse_operations operations_;
Oh right.

2020-11-29 04:04 UTC, shu-g commented on include/sadfs/sadfsd/sadfilesys.hpp
> +#include <memory> // std::shared_ptr
Oh right.

2020-11-29 04:23 UTC, shu-g commented on include/sadfs/sadfsd/sadfilesys.hpp
> +    // returns static pointer to object of this class
modified it to:
retrieves instance of this class with the help of fuse_get_context() and returns a static pointer to it

2020-11-29 04:23 UTC, shu-g commented on include/sadfs/sadfsd/sadfilesys.hpp
> +    int run(int argc, char** argv);
Yeah works

2020-11-29 04:24 UTC, shu-g commented on include/sadfs/sadfsd/sadfuse.hpp
> +#endif // SADFS_SADFSD_SADFUSE_HPP
Yup

2020-11-30 18:46 UTC, shu-g commented on src/CMakeLists.txt
> +endforeach()
I should've asked this in the patch-2 review but anyway:
Why should TARGET-bootstrap be built before TARGET?
In line #59, why does BOOTSTRAP_TARGET need to be linked against sadfs_protobuf?

2020-11-30 20:45 UTC, damanmkumar commented on src/CMakeLists.txt
> +endforeach()
We add it as a dependency only for the sake of convenience. Since we need the bootstrap targets to start our main server processes, it makes sense to also build `sadmd-bootstrap` when you run `make sadmd`. There isn't any dependency code-wise!

Linking the bootstrap targets against `sadfs_protobuf` is just something that used to be relevant, but no longer is. The original idea was to get the bootstrap process to pass some information to the main process using protobufs. It can be safely removed now. Feel free to either do it now, or raise an issue -- we can take care of it later.

2020-11-30 20:47 UTC, damanmkumar approved these changes
LGTM

2020-11-30 20:47 UTC, merged