Created functions to maintain list of servers
CS297P-SAD/sadfs pull request #43
Opened 2020-11-25 20:02 UTC by abmono93

Closes #31

2020-11-25 21:52 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +using nanosec = std::chrono::steady_clock::duration::rep;
`steady_clock` has a type `rep` as well, which I think is the same as `steady_clock::duration::rep`. Using `steady_clock::rep` is cleaner.

Also, it doesn't represent nanoseconds, but the number of ticks since the epoch. So, the alias should maybe be `ticks`?

2020-11-25 21:54 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +	bool is_active(serverid) const noexcept;
This works for now, but should be handled by a different entity. `sadmd` now has way too many responsibilities.

2020-11-25 21:55 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +using serverid = uint64_t;
We should merge `chunkid` and `serverid` into `uuid`. Their "type" is essentially the same.

2020-11-25 21:56 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +}
Let's get rid of this. We need a function that accepts a time interval and returns the corresponding TTL.

2020-11-25 21:59 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +}
Maybe a template will be a good idea.

2020-11-25 21:59 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +}
This should be a wrapper around the function that accepts a time interval, with the interval set to `0min` or `0s`.

2020-11-25 22:01 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +			0, // chunk count is zero to start
When a chunk server registers with a master server upon restart, it should advertise the number of chunks it owns. So, it will be 0 only in special cases.

2020-11-25 22:03 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	auto server = &chunk_server_metadata_.at(id);
We should check if the `id` is a registered server in the first place. `at(id)` will throw an exception if `id` does not exist, if I'm not mistaken.

2020-11-25 22:03 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	auto server = &chunk_server_metadata_.at(id);
Why are we using a pointer here? A reference will work just fine, won't it?

2020-11-25 22:05 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	server->ttl = time::in_1_min();
This will call/use our parameterized function. Maybe: `server.ttl = time::in(1min);`

2020-11-25 22:06 UTC, damanmkumar requested changes
A few comments

2020-11-25 22:37 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +using serverid = uint64_t;
This is for readability. e.g. on lines 71-73 it makes the distinction between `chunk_server_metadata_` and `chunk_locations_` very intuitive. Also something like `is_active(serverid)` is self documenting vs. `is_active(uuid)`

2020-11-25 22:53 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +			0, // chunk count is zero to start
It also needs to tell the master which chunks it owns, not just how many, so that `chunk_locations_` is up to date. I think we'll need one function like `add_chunk_to_server()` which updates `chunk_locations_` and increments this field. After the chunk server has joined the network it can send individual control messages for each chunk, just like when it gets new chunks.

2020-11-25 23:08 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	auto server = &chunk_server_metadata_.at(id);
I can't remember exactly but it had something to do with the fact that there's no default constructor for `inet::service` which is a member variable of `chunk_server_info`. Maybe when was when trying to use brackets. Anyway I've changed it so we just update ttl directly without creating a local variable

2020-11-26 00:13 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +using nanosec = std::chrono::steady_clock::duration::rep;
I agree but maybe just `tick`. My thinking is it's `int` not `ints`

2020-11-26 01:29 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +using nanosec = std::chrono::steady_clock::duration::rep;
`tick ttl;` definitely doesn't read right. And now that we discussed it, neither does `ticks ttl;`.
The number of people in a room is a "head count."
The number of ticks after which an entry is no longer valid is a... "tick count?"
Like so: `tick_count ttl;`

BUT, what `ttl` really is is a point in time in the future, that we are representing as an integer that encodes the number of ticks since an epoch. So, `time_point` is probably the most representative of our idea. What do you think?

2020-11-26 01:33 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +using nanosec = std::chrono::steady_clock::duration::rep;
With `time_point`, our functions will read better as well. `time::in(duration d)` returns a `time_point` which is time-duration `d` away from this moment in time.

2020-11-26 02:00 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +using serverid = uint64_t;
Well, `map<uuid, data> server_metadata` and `map<uuid, server_info> chunk_locations` tell the reader that they are mapping the uuid of a server to its metadata, and the uuid of a chunk to its location. `is_active` is a very generic function name, and shouldn't be a private member function of the master server anyway. So, I'm not convinced with the second reason.

But, being explicit about `serverid` and `chunkid` in the declarations of the unordered maps is convincing enough.

2020-11-26 02:39 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +			0, // chunk count is zero to start
Sending a message over the network has a sizable overhead. So, we definitely should exploit this registration message to also send in the list of chunks that the chunk server owns.

However, the number of chunks on a server could theoretically be huge enough to make our protobuf larger than 1 MB (which is when google suggests we think of an alternate strategy). So, how about we send in the list of chunks with the registration message as well?

In the case that the list is very large, we send an empty list, and then register the chunks in batches. As a first step, implementing just the first case should be good enough. In that case, the initial chunk count should be a parameter (or however we're passing in `available_chunks`.

That reminds me -- `available_chunks` sounds like a list/count of chunks that are available for clients to read/write.

2020-11-26 02:44 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	chunk_server_metadata_.at(id).ttl = time::in(1min);
Can we wrap `time::in(1min)` into a function or make the `1min` a default value? Just so we don't introduce bugs later if we decide to change this to a different value, and not update it in some places.

2020-11-26 02:57 UTC, damanmkumar requested changes
A couple more comments

2020-11-26 03:07 UTC, abmono93 commented on include/sadfs/sadmd/sadmd.hpp
> +using nanosec = std::chrono::steady_clock::duration::rep;
That's kind of what I was going for with `nanosec` I guess. It's a particular nanosecond that could be in the future or past. But you're right that if a tick isn't a nanosecond it's not the right name. I can't think of something better than `time_point` so I'll go with that

2020-11-26 03:13 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	chunk_server_metadata_.at(id).ttl = time::in(1min);
I came across a nice solution while going to change this: we just have an optional argument that defaults to one minute. It's not as intuitive to read as `time::in(1min)` so maybe `in()` should be changed. But there's the added benefit that you don't need to have `namespace std::literals` every time you call this which is a little clunky

2020-11-26 03:23 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +			0, // chunk count is zero to start
Yea that is true. What about a separate control message for a server to "claim" one or more chunks in a batch? Then adding a server takes 1 message for a brand new server and 2 for a server restarting.

And I agree that `available_chunks` isn't a great name. I just didn't want to confuse it with `max_chunks` and this is the best I came up with. Do you have any ideas?

2020-11-27 19:53 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	chunk_server_metadata_.at(id).ttl = time::in(1min);
After reviewing this again I came up with a slightly different approach. I renamed `chunk_server_info.tll` to `chunk_server_info.expiration_point` since it's a better description of how this variable is used. Then I defined 2 constants `server_ttl` and `file_ttl`, and `in()` is now called `future()` and is meant to take in one of those two constants to set the expiration point. lmk if you think this works

2020-11-27 21:35 UTC, shu-g commented on src/sadmd/sadmd.cpp
> +			0, // chunk count is zero to start
Even if we assume that the chunk server holds 1TB data, we will have 1TM/64MB chunks i.e. 2^(40 - 26) or 2^14 chunks. If the UUID for each chunk consumes 8B, the space consumed by the list will be 2^(14+3) B which is less than 1MB.
So, I also think we should send the UUIDs with the control message at this point.
How about `stored_chunks`?

2020-11-27 23:39 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +			0, // chunk count is zero to start
UUIDs are 128-bits i.e., 16 bytes. Even if that is the case, Shubham's observation holds true. A protobuf will be a little over 256KB

2020-11-28 00:12 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +future(std::chrono::minutes delta) noexcept
`future` has a different meaning in computer science: https://en.wikipedia.org/wiki/Futures_and_promises
It also doesn't read right. How about `time::from_now(server_ttl)/time::from_now(1min)` ?

2020-11-28 00:14 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +current() noexcept
I feel `time::now()` sounds better, and is used everywhere in general. Agree?

2020-11-28 00:14 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +constexpr auto file_ttl = 1min;
This is a great idea!

2020-11-28 00:15 UTC, damanmkumar requested changes
Two comments

2020-11-28 00:44 UTC, merged

2020-11-28 00:44 UTC, damanmkumar reviewed
approved