Create chunkid and uuid
CS297P-SAD/sadfs pull request #55
Opened 2020-12-02 19:51 UTC by abmono93

- Includes merged in uuid branch
- Redefined chunkid as alias for uuid instead of unsigned int
- Redefined internal protobuf for new chunkid definition, including wrapper class (which also replaces serialize and deserialize functions in sadmd.cpp)
- Implemented sadmd::add_chunk_to_file()
- Cleaned up error handling in create_file (I was planning to do this separately but it made sense to do it here during testing)

Closes #54 
Closes #32

2020-12-03 04:09 UTC, damanmkumar commented on src/comm/internal.proto
> +}
The file looks good, but it should be in `src/proto/internal/` so that it matches the `package` statement. Maybe we should rename the file to util(s).proto ?

2020-12-03 04:15 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +namespace sadfs {
How about renaming this file to `util.hpp`, and moving its contents into the `sadfs::sadmd::util` namespace?

2020-12-03 04:31 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +        protobuf_.add_uuids(to_string(id));
The `to_string` function returns a human-readable representation of the `uuid`, like `d0f34638-46c5-4c03-8ef7-7f0004af99fd`. We should be using the `uuid::serialize` function to serialize the `uuid` into 8 bytes.

One way to do it would be to create a temporary string, serialize the `uuid` to it, and move it into the protobuf (to avoid a copy).

2020-12-03 05:31 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +        }
Let's not handle what is obviously a programming error. This will help hide bugs in our code. We should either directly call `protobuf_.uuids(i)`, or throw an exception after performing bounds checking.

That said, what is the use case for this operator? At the server side, we simply serialize from a `vector<uuid>`, and at the client side deserialize into a `vector<uuid>`, right?

2020-12-03 05:34 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +    size_t size()
Let's specify that this is `std::size_t` so that there is no ambiguity. It's fine to not specify `std::` for `uint64_t` since that specifies the width explicitly.

2020-12-03 05:34 UTC, damanmkumar commented on include/sadfs/sadmd/sadmd.hpp
> +#include <boost/container_hash/hash.hpp>
No longer required, right?

2020-12-03 05:44 UTC, abmono93 commented on include/sadfs/sadmd/internal.hpp
> +        }
Good point, we don't really need error checking.

The intention for this class was to use an internal protobuf instead of a vector. The use case is when a client asks for the ith chunk of `filename`, we can find it in `files[filename].chunkids[i]` as if it were in a vector.

2020-12-03 05:52 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +        }
Oh, damn, I had it completely mixed up in my head. Yup, this looks good. If you decide to throw, rename the function to `at(std::size_t i)`. If you decide to simply call `uuids(i)`, the operator overload is perfect.

2020-12-03 05:53 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +        }
One comment, though. Since this is an in-line definition, let's not move the name of the function to a separate line.

2020-12-03 05:57 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +		info.chunkids.deserialize(existing_chunks);
I don't have a comment for this line, but the function name `create_file` doesn't make sense in the context of `load_files`, right? We have a different use case for file "creation." Maybe `load_file` is better?

2020-12-03 06:10 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +    void add_chunk(uuid const& id)
Since we're `using chunkid = sadfs::uuid`, let's keep it consistent, and use the same type alias here as well.

2020-12-03 06:11 UTC, damanmkumar commented on src/comm/internal.proto
> +    repeated bytes uuids = 1;
For consistency, how about we name this field `chunkids`?

Also, ignore my comment about moving this file to `src/proto/`. That change hasn't been merged in yet.

2020-12-03 06:16 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	auto new_chunkid = chunkid::generate();
The master server will generate a chunkid and send it to the client upon a request to create a new chunk. Then, upon successful write to the main chunk server, and receipt of a control message from the chunk server informing the master server of a new chunk, the master will add that chunkid to its in-memory store. So, this method should take a chunkid as a parameter.

2020-12-03 06:20 UTC, damanmkumar requested changes
Left a few comments, all of them minor

2020-12-03 18:06 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +		info.chunkids.deserialize(existing_chunks);
This function can be used both to create new files in an active system and to "load" files on a master that's just started. The way I think of it is we have recorded there was a file with such and such properties. Now that the system is restarting, we need to create (or I guess recreate) it.

That is also the reason we have the existing chunks as an optional argument.

2020-12-03 18:20 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	auto new_chunkid = chunkid::generate();
I don't think that's the right approach. The use case here is a client wants to add a new chunk to a file, either because the file has been created and nothing written to it yet or the last chunk of the file is full. So the master needs to generate a new unique ID for this new chunk and should record this chunk exists upon creation for a couple reasons:
- one of the inherent properties of this chunk is its the first (or second etc..) chunk of `filename`, so this ensures that the list of chunks is in the right order
- now when a server tells the master it has written this chunk, the master is already aware it exists and adds that server to its (previously empty) list of locations. This ensures no chunks are added to the system except those generated by the master

2020-12-03 18:25 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	auto new_chunkid = chunkid::generate();
Actually ignore this^ I have a better idea

2020-12-03 18:36 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +		info.chunkids.deserialize(existing_chunks);
It doesn't make sense for the two use cases to use the same function. At the very least, this function should be called `load_file`, with `create_file` maybe being a wrapper around it like
```
create_file(... filename)
{
    ...
    load_file(filename, std::string{}); // new file -- no chunks
    ...
}
```
simply because we are implementing file creation by loading it now, and assuming it will be persisted later.

2020-12-03 19:52 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	auto new_chunkid = chunkid::generate();
Ok my idea didn't end up working out but I renamed this function to `append_chunk_to_file` and changed some other things. Lmk if the current version makes sense to you.

2020-12-04 00:04 UTC, abmono93 commented on include/sadfs/sadmd/internal.hpp
> +        protobuf_.add_uuids(to_string(id));
I couldn't easily get this to work without mangling some of the uuids after restarting the server... obviously I'm doing something wrong. But this protobuf isn't getting sent over the network anyway, it's just for sadmd to use instead of a vector and to speed up saving files in the database. So I think it's okay the way it is even if it's not ideal

2020-12-04 04:43 UTC, damanmkumar commented on include/sadfs/sadmd/util.hpp
> +    chunkid operator[](unsigned int const i)
`protobuf_.chunkids(i)` expects an `int`. Let's change `i`to just be an `int`. This will be an issue once we enable warnings on our code base, since it will complain about narrowing.

2020-12-04 04:45 UTC, damanmkumar commented on include/sadfs/sadmd/util.hpp
> +namespace sadfs { namespace util {
Namespaces should (mostly) match the location they're in or logical partitions. So, this should be in `sadfs::sadmd::util` because it contains utility components for `sadmd` and all of sadfs in general.

2020-12-04 04:46 UTC, damanmkumar commented on include/sadfs/sadmd/util.hpp
> +        protobuf_.add_chunkids(to_string(id));
Let's address this during our meeting tomorrow morning.

2020-12-04 04:52 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +create_file(std::string const& filename)
Shouldn't this be the other way around, where `create_file` calls `load_file` with an empty `std::string`? Because, logically, when we want to create a file, we "load" it into our in-memory data structure -- assuming that it will be persisted to disk during shutdown, thus creating it.

2020-12-04 04:55 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	auto file_chunkids  = &(files_[filename].chunkids);
We don't have to play with pointers here. References will work without creating copies, like it currently does with the call to `reintroduce_chunks_to_network`.
```
auto& file_chunkids = files_[filename].chunkids;
file_chunkids.deserialize(...);
reintroduce...(file_chunkids);
```

```
void reintroduce_chunks_to_network(file_chunks& chunks);
```

2020-12-04 04:57 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +void sadmd::load_file(std::string const& filename, std::string const& existing_chunks)
The function name needs to appear on a new line.

2020-12-04 05:18 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +create_file(std::string const& filename)
Also, if we add a constructor to file_chunks that takes a string and deserializes the protobuf from it, our code will be much cleaner. We will no longer need to add an entry to `files_` and then retrieve the value to  deserialize it from a string.

2020-12-04 05:26 UTC, damanmkumar commented on src/sadmd/sadmd.cpp
> +	auto new_chunkid = chunkid::generate();
The scenario I am concerned about is this:
- master server generates a chunkid and adds it to the required file, and into `chunk_locations_`
- the write operation fails

Now we have an inconsistent state. You raised a terrific point about adding a chunkid that we cannot guarantee was generated by us. One way to address both issues is to add this newly generated chunkid into a `tentative_chunkids` list, and leaving the `files_` structure unmodified.

Later, when chunk servers inform the master server of new chunkids, we can verify it against this list before modifying `files_` and `chunk_locations_`.

2020-12-04 10:32 UTC, damanmkumar commented on include/sadfs/sadmd/internal.hpp
> +        protobuf_.add_uuids(to_string(id));
Can you take a look at #57 ? If it doesn't work out of the box with your tests, we can address it sometime later.

2020-12-04 17:49 UTC, abmono93 commented on include/sadfs/sadmd/internal.hpp
> +        protobuf_.add_uuids(to_string(id));
Thanks, that worked

2020-12-04 18:04 UTC, abmono93 commented on src/sadmd/sadmd.cpp
> +	auto new_chunkid = chunkid::generate();
That's a good point but I think we can handle that without creating another data structure that would need to be managed. What would happen is the write operation fails for some reason and the client gives up. Eventually their write lock on this file expires. Now the next time someone tries to write, master behaves exactly as in any other situation when the last chunk of the file isn't full. i.e. instead of generating another chunkid, it looks at this file and sees that more data can fit on the last chunk. It then tells the client the chunkid and which server(s) to write it to. The only potential issue is the master has to recognize what to do when `server_locations_[chunkid]` is empty. But that also happens any time new data is written to a chunk, so we already have to implement this decision process.

2020-12-04 18:10 UTC, abmono93 commented on include/sadfs/sadmd/util.hpp
> +namespace sadfs { namespace util {
I just tried implementing this but realized`sadmd` is already the name of a class

2020-12-04 18:58 UTC, damanmkumar approved these changes
LGTM

2020-12-04 18:58 UTC, merged