Implement sadfilesys::read()
CS297P-SAD/sadfs pull request #94
Opened 2020-12-11 20:25 UTC by shu-g

* Move bytes_per_chunk to sadfs/constants.hpp
* Implement read()
* Modify assigned errors

Doesn't build, dependencies yet to be merged.

2020-12-12 22:07 UTC, abmono93 approved these changes
Looks great

2020-12-12 23:16 UTC, damanmkumar commented on include/sadfs/constants.hpp
> +constexpr auto bytes_per_chunk = 64 * 1024 * 1024; // 64MB
Let's add this to the `constants` namespace

2020-12-12 23:18 UTC, damanmkumar commented on src/sadcd/heart.cpp
> +    while (stop_token.wait_for(15s) != std::future_status::ready)
Isn't 15 seconds too long a time duration? 1 second is pretty long itself, especially when we're talking about a system like this. But, anything over 5 seconds is way too long, IMO

2020-12-12 23:20 UTC, damanmkumar commented on src/sadcd/sadcd.cpp
> +
#98 implements this functionality. 
You might need a local copy of this for testing on your end.

2020-12-12 23:21 UTC, damanmkumar commented on src/sadfsd/sadfilesys.cpp
> +    	strcmp(path, "/autorun.inf") == 0)
What are `/.` and `/autorun.inf` ?

2020-12-12 23:23 UTC, damanmkumar commented on src/sadfsd/sadfilesys.cpp
> +                      std::string(strerror(-result)));
This reads like a message logged by someone that calls `getattt`. Our debug statement should help us figure out what sadfilesys is doing, which is rejecting this request because it is for `/.` or `/autorun.inf`

2020-12-13 02:51 UTC, damanmkumar requested changes
Left a couple of comments a while ago

2020-12-13 04:21 UTC, shu-g commented on include/sadfs/constants.hpp
> +constexpr auto bytes_per_chunk = 64 * 1024 * 1024; // 64MB
Oh right.

2020-12-13 04:34 UTC, shu-g commented on src/sadcd/heart.cpp
> +    while (stop_token.wait_for(15s) != std::future_status::ready)
I modified it to 15s to make it easier for me to parse logs during testing.
I would think in an actual system, it should be on the order of minutes since it is unlikely that multiple servers fail within that span and the request can still be served to client through the other chunk servers.
Also heartbeat every second from 10-50 chunk servers is unnecessarily creating network traffic and load at the master server. I don't see the requirement for strict consistency in our use case between master and chunk server.

2020-12-13 04:39 UTC, shu-g commented on src/sadcd/sadcd.cpp
> +
Yep, will keep a copy.

2020-12-13 04:47 UTC, shu-g commented on src/sadfsd/sadfilesys.cpp
> +    	strcmp(path, "/autorun.inf") == 0)
When the filesystem is mounted, I observe requests by the OS to a couple of hidden files like /.Trash, /.Trash1000 and to the file /autorun.inf. We should be able to remove them when we start testing with actual sadmd, we'll get not-ok from the master server and return error. At the moment using dummy-sadmd, we return ok for every request and then the os tries to read these files that don't exist.

2020-12-13 04:51 UTC, damanmkumar commented on src/sadcd/heart.cpp
> +    while (stop_token.wait_for(15s) != std::future_status::ready)
I see what you mean, but shouldn't our number one priority be fast access for clients of the FS? If a popular server goes down, and we serve its IP to all those clients for a few minutes, it would be a disaster (hyperbole, definitely). I think it is realistic for a master server to be serving hundreds of thousands of requests per second at a minimum, and a few hundred lightweight heartbeat requests should be insignificant.

2020-12-13 18:19 UTC, merged